eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
logging:
  level:
    org:
      springframework:
        '*': info
server:
  port: 8082
spring:
  application:
    name: department-description
  devtools:
    restart:
      enabled: true
