eureka:
  client:
#    fetch-registry: true
#    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org:
      springframework:
        '*': info
server:
  port: 0
spring:
  application:
    name: department-catalogue
  devtools:
    restart:
      enabled: true
